# permissions for end users to view gremlins.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gremlin-viewer-role
rules:
- apiGroups:
  - gremlin.com
  resources:
  - gremlins
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - gremlin.com
  resources:
  - gremlins/status
  verbs:
  - get
