# permissions for end users to edit gremlins.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gremlin-editor-role
rules:
- apiGroups:
  - gremlin.com
  resources:
  - gremlins
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - gremlin.com
  resources:
  - gremlins/status
  verbs:
  - get
